### ISSUE TITLE
Does not support new Origen app dir structure

### ISSUE THREAD

**Issue by redxeth** [Origen-SDK/origen_doc_helpers#19]
Apps that use Origen `app/` dir workspace structure appears to have issues with this plug-in.  Pages generated for have incorrect links in them.  

As an example I am trying to render `doc_helpers/searchable.html` in order to implement a searchable set of guides. I have to pass in a valid `:root` option to the render otherwise I'll get a compile error:

    % opts = options.merge(index: index, root: "#{Origen.root}/app/templates/web/guides/", pdf_title: "My Guides")
    % render "doc_helpers/searchable.html", options.merge(opts) do
    <%= yield %>

    % end
    
However then my links include `app/templates/web/guides` which is incorrect.  

Older apps pass in this: 

    % opts = options.merge(index: index, root: "#{Origen.root}/templates/web/guides/", pdf_title: "My Guides")
    % render "doc_helpers/searchable.html", options.merge(opts) do
    <%= yield %>

    % end
    
and yet the doc helpers is able to correctly render the internal links to `latest/` and not `/templates/web/guides/`.   

I suspect it's a matter of having the plugin know which type of app (old or new structure) it is dealing with.

**Comment by pderouen** [comment]
@redxeth I think this method is the one that requires an update: https://github.com/Origen-SDK/origen_doc_helpers/blob/14c284551d8ac23dfc15c4c33e8033eab755603e/lib/origen_doc_helpers/helpers.rb#L291

**Comment by pderouen** [comment]
Maybe the easiest fix is to use "#{Origen.root}/templates/web" if it exists, else use the new app structure path.

**Comment by redxeth** [comment]
I did the opposite-- if "#{Origen.root}/app/" exists (indicating using struct) then use it, else use old method.  But basically the same thing.
